### PR TITLE
added several decktypes for TESL

### PR DESCRIPTION
**Pull request by ittyzoffeji**

### CODE REVIEW

**Comment by extesy** [comment]
Thank a lot, @ittyzoffeji! I have noticed that some of the archetypes in your list only include one card, for example all archer and assassin subtypes. Are you sure it's a good idea? If some deck includes matching cards from several archetypes then the deck will be classified only on a higher level, like just "assassin". It's certainly better classification that it was before but I wonder if it can be made a bit more accurate.

**Comment by ittyzoffeji** [comment]
Hi, extesy! Thank you for your DeckTracker! Definitely the best tracker for TESL right now.
You are right, decks classification is not ideal, but I'm not sure how to make it more accurate at the moment. For most decks with only one card you can be pretty sure about their type just based on this card, at least in the current meta.
 Do you have documentation on how to use decktypes.txt? What will happen if there are two decks with the same name on the same sub-level? For example, if I see "Swindler's Market" card in Archer, it's Swindler's deck 100%. If my opponent plays "Raiding Party",  "Merchant's Camel", and "Goblin Skulk", I'm 90% sure it's a Swindler's Archer. If I put two lines like this:

|||Swindler's Market|Cards.Contains("Swindler's Market")
|||Swindler's Market|Cards.Contains("Raiding Party","Merchant's Camel","Goblin Skulk")

what will happen? Or maybe there is a better way to handle situations like this? 
Also is there a way to exclude cards?

**Comment by extesy** [comment]
@ittyzoffeji The syntax of the condition is a plain C# so you can put any valid C# expression there. So if you for example want to write "A or B" condition then it would look like this this:

> |||Swindler's Market|Cards.Contains("Swindler's Market") || Cards.Contains("Raiding Party","Merchant's Camel","Goblin Skulk")

The system tries to find the unique match on a deepest level. If multiple archetypes on the same level match then the level above is compared, etc. So if the deck matches both Goblins and Swindler's Market conditions then it would be reported as just Assassin.

You can also add additional sublevels by adding one more `|` in the beginning. Each sublevel assumes that conditions of all levels above are already satisfied. You can see examples for Eternal doing this: Clockroach Possibilities or Scream Reanimator.

By the way, you can test your changes locally if you create `C:\Users\{profile}\AppData\Roaming\UniversalDeckTracker\decktypes.txt` file.

**Comment by ittyzoffeji** [comment]
OK, thanks for the info. I'll play with it locally and hopefully come up with better decktypes in a few days.

**Pull request merged**
