### PR TITLE
More decktypes - Eternal

### PR DESCRIPTION
**Pull request by AustinYQM**
Adds:

- Elysian Midrange
- Feln Control
- Hooru Control
- Praxis Tokens
- Infinite Gunsmiths
- TJP Control
- TJP Midrange
- TJP Shimmerpack

Changes:

- Scream Reanimator
- FJS Armory

See if the way I did TJP Shimmerpack works. I was trying to accomplish `If( (Colors == TJP) && (Cards == Shimmer Pack) && ( (Cards == Xenan Obelisk) OR (Cards == Scouting Party) OR (Cards == Marisen's Disciple) ) ){ DeckType = TJP Shimmerpack } ;` but I am only half sure that is even possible.

### CODE REVIEW

**Comment by AustinYQM** [comment]
```
If(Colors == TJP) {
     If(Cards == Shimmerpack) {
          If(Cards == (Scouting Party OR Marisen's Disciple OR Xenan Obelisk) {
               DeckType = TJP Shimmer Pack ;
          }
     }
}
```

**Comment by extesy** [comment]
@AustinYQM The part after the archetype name is actually plain `C#` code so you can do stuff like `Cards.Contains("Shimmerpack") && Cards.ContainsAny(1,"Xenan Obelisk","Scouting Party","Marisen's Disciple")`

**Comment by extesy** [comment]
Also, your `Feln Control` was broken (should be a subtype of `Feln`, not on the same level). I fixed it in the merge.

**Comment by AustinYQM** [comment]
Awesome to know.

**Pull request merged**
